// data/data.js
const categories = [
  {
    id: 'clapiers-lapin',
    name: 'Clapiers Lapin',
    products: [
      { id: '1-1', name: 'Clapier intérieur', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/clapier-interieur' },
      { id: '1-2', name: 'Clapier extérieur', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-exterieur' },
      { id: '1-3', name: 'Clapier en bois', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-en-bois' },
      { id: '1-4', name: 'Clapier en béton', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-en-beton-pour-lapin' },
      { id: '1-5', name: 'Clapier avec enclos', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-lapin-avec-enclos' },
      { id: '1-6', name: 'Clapier intérieur/extérieur', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-lapin-interieurexterieur' },
      { id: '1-7', name: 'Clapier en bois avec plateaux', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-lapin-en-bois-avec-plateaux' },
      { id: '1-8', name: 'Clapier extérieur avec double enclos', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-lapin-exterieur-avec-double-enclos' },
      { id: '1-9', name: 'Clapier extérieur avec plateau excrement', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-lapin-exterieur-avec-plateau-excrement' },
      { id: '1-10', name: 'Clapier extérieur en bois à râtelier', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-lapin-exterieur-en-bois-a-ratelier' },
      { id: '1-11', name: 'Clapier extérieur en bois avec toit ouvrant', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-lapin-exterieur-en-bois-avec-toit-ouvrant' },
      { id: '1-12', name: 'Clapier extérieur en bois résistant à l\'hiver', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-lapin-exterieur-en-bois-resistant-a-lhiver' },
      { id: '1-13', name: 'Clapier extérieur enclos et terrasse', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-lapin-exterieur-enclos-et-terasse' },
      { id: '1-14', name: 'Clapier extérieur/extérieur en bois', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-lapin-exterieurinterieur-en-bois' },
      { id: '1-15', name: 'Clapier extérieur/extérieur en bois avec cage', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-lapin-exterieurinterieur-en-bois-avec-cage-' },
      { id: '1-16', name: 'Clapier extérieur/extérieur enclos', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-lapin-exterieurinterieur-enclos' },
      { id: '1-17', name: 'Clapier extérieur toit ouvrable', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-lapin-exterieur-toit-ouvrable' },
      { id: '1-18', name: 'Clapier extérieur triangulaire en bois', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-lapin-exterieur-triangulaire-en-bois' },
      { id: '1-19', name: 'Clapier extérieur XXL en bois', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-lapin-exterieur-xxl-en-bois' },
      { id: '1-20', name: 'Clapier intérieur à plateaux amovibles', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-lapin-interieur-a-plateaux-amovibles' },
      { id: '1-21', name: 'Clapier intérieur à toit ouvrant', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-lapin-interieur-a-toit-ouvrant' },
      { id: '1-22', name: 'Clapier intérieur avec toit ouvrant', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-lapin-interieur-avec-toit-ouvrant' },
      { id: '1-23', name: 'Clapier intérieur en bois avec niche', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-lapin-interieur-en-bois-avec-niche' },
      { id: '1-24', name: 'Clapier intérieur en bois plateau glissant', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-lapin-interieur-en-bois-plateau-glissant' },
      { id: '1-25', name: 'Clapier intérieur sur pieds', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-lapin-interieur-sur-pieds-' },
      { id: '1-26', name: 'Clapier intérieur XXL', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/clapier-lapin-interieur-xxl' },
    ],
  },
  {
    id: 'cages-lapin',
    name: 'Cages Lapin',
    products: [
      { id: '2-1', name: 'Cage intérieur', rating: 5.0, comment: 'Produit exceptionnel!', url: 'https://clapier-lapin.pro/cage-interieur' },
      { id: '2-2', name: 'Cage extérieur', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-exterieur' },
      { id: '2-3', name: 'Cage de transport', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-de-transport' },
      { id: '2-4', name: 'Cage XXL', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-xxl' },
      { id: '2-5', name: 'Cage avec 2 portes', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-avec-2-portes-122-x-745-cm' },
      { id: '2-6', name: 'Cage avec 4 panneaux verrouillables', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-avec-4-panneaux-verrouillables' },
      { id: '2-7', name: 'Cage avec aérations et sécurité', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-avec-aerations-et-securite' },
      { id: '2-8', name: 'Cage de transport Trixie Pico', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-de-transoirt-trixie-pico-23x16x17-cm' },
      { id: '2-9', name: 'Cage intérieur avec hamac et cube de rangement', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-dinterieur-avec-hamac-et-cube-de-rangement' },
      { id: '2-10', name: 'Cage étanche pour petits animaux', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-etanche-pour-petits-animaux' },
      { id: '2-11', name: 'Cage et enclos pour animaux 60cm', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-et-enclos-pour-animaux-60cm' },
      { id: '2-12', name: 'Cage et petit animal en plastique recyclé', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-et-petit-animal-en-plastique-recycle' },
      { id: '2-13', name: 'Cage extérieur 220x103x103 cm', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-exterieur-220x103x103-cm' },
      { id: '2-14', name: 'Cage extérieur et cochon d\'inde avec séparation', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-exterieur-et-cochon-dinde-avec-separation' },
      { id: '2-15', name: 'Cage extérieur/intérieur 2 étages avec accessoires', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-exterieurinterieur-2-etages-avec-accessoires' },
      { id: '2-16', name: 'Cage Feandrea enclos métallique noir', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-feandrea-enclos-metallique-noir' },
      { id: '2-17', name: 'Cage Ferplast 100 pour rongeurs', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-ferplast-100-pour-rongeurs' },
      { id: '2-18', name: 'Cage Ferplast vert pour rongeurs', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-ferplast-vert-pour-rongeurs' },
      { id: '2-19', name: 'Cage intérieur avec 2 portes', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-interieur-avec-2-portes' },
      { id: '2-20', name: 'Cage intérieur enclos cochon d\'inde', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-interieur-enclos-cochon-dinde' },
      { id: '2-21', name: 'Cage intérieur Midwest Critter Nation avec support', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-interieur-midwest-critter-nation-avec-support' },
      { id: '2-22', name: 'Cage Kerbl box de transport pour chien', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-kerbl-box-de-transport-pour-chien' },
      { id: '2-23', name: 'Cage Kerbl Expedion 45x30x30 cm', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-kerbl-expedion-45x30x30-cm' },
      { id: '2-24', name: 'Cage Kerbl Gabbia Baldo 100x53x46 cm', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-kerbl-gabbia-baldo-100x53x46-cm' },
      { id: '2-25', name: 'Cage Kerbl Gulliver 48x32x31 cm gris', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-kerbl-gulliver-48x32x31-cm-gris' },
      { id: '2-26', name: 'Cage Kerbl Pet IATA 3 60 x 40 cm', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-kerbl-pet-iata-3-60-x-40-cm' },
      { id: '2-27', name: 'Cage métal 6 panneaux 80x80 cm', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-metal-6-panneaux-80x80-cm' },
      { id: '2-28', name: 'Cage métal extra large facile à assembler', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-metal-extra-large-facile-a-assembler' },
      { id: '2-29', name: 'Cage modulable pour petits animaux', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-modulable-pour-petits-animaux' },
      { id: '2-30', name: 'Cage MP Bergamo panier transport Gipsy 50', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-mp-bergamo-panier-transport-gipsy-50' },
      { id: '2-31', name: 'Cage multi niveaux 6 étages pour rongeurs', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-multi-niveaux-6-etages-pour-rongeurs' },
      { id: '2-32', name: 'Cage pliable anthracite respirante', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/-cage-lapin-pliable-anthracite-respirante' },
      { id: '2-33', name: 'Cage pliable XL avec 2 portes', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-pliable-xl-avec-2-portes' },
      { id: '2-34', name: 'Cage roulante 3 étages avec rampes', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-roulante-3-etages-avec-rampes' },
      { id: '2-35', name: 'Cage Savic Elmo taille L', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-savic-elmo-taille-l' },
      { id: '2-36', name: 'Cage spacieuse avec accessoires inclus', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-spacieuse-avec-accessoires-inclus' },
      { id: '2-37', name: 'Cage transport respirante et pliable', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-transport-respirante-et-pliable' },
      { id: '2-38', name: 'Cage XXL 120 cm', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/cage-lapin-xxl-120-cm' },
    ],
  },
  {
    id: 'enclos-lapin',
    name: 'Enclos Lapin',
    products: [
      { id: '3-1', name: 'Enclos intérieur', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-interieur' },
      { id: '3-2', name: 'Enclos extérieur', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/enclos-exterieur' },
      { id: '3-3', name: 'Enclos modulable', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/enclos-modulable' },
      { id: '3-4', name: 'Enclos intérieur et extérieur 6 panneaux', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-lapin-interieur-et-exterieur-6-panneaux' },
      { id: '3-5', name: 'Enclos intérieur et extérieur robuste', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-lapin-interieur-et-exterieur-robuste' },
      { id: '3-6', name: 'Enclos intérieur modulable noir 109x74x109cm', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-lapin-interieur-modulable-noir-109x74x109cm' },
      { id: '3-7', name: 'Enclos métal modulable robuste', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-lapin-metal-modulable-robuste' },
      { id: '3-8', name: 'Enclos métal modulaire 12 panneaux', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-lapin-metal-modulaire-12-panneaux' },
      { id: '3-9', name: 'Enclos modulable 2 niveaux 143x73 cm', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-lapin-modulable-2-niveaux-143x73-cm' },
      { id: '3-10', name: 'Enclos modulable 2 niveaux noir', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-lapin-modulable-2-niveaux-noir' },
      { id: '3-11', name: 'Enclos modulable avec bâche', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-lapin-modulable-avec-bache' },
      { id: '3-12', name: 'Enclos modulable avec porte métal', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-lapin-modulable-avec-porte-metal' },
      { id: '3-13', name: 'Enclos modulable blanc 175x75x35 cm', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-lapin-modulable-blanc-175x75x35-cm' },
      { id: '3-14', name: 'Enclos modulable DIY 47 panneaux noir', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-lapin-modulable-diy-47-panneaux-noir' },
      { id: '3-15', name: 'Enclos modulable intérieur 12pcs', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-lapin-modulable-interieur-12pcs' },
      { id: '3-16', name: 'Enclos modulable Pawhut 24 panneaux noir', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-lapin-modulable-pawhut-24-panneaux-noir' },
      { id: '3-17', name: 'Enclos modulable pour rongeurs', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-lapin-modulable-pour-rongeurs' },
      { id: '3-18', name: 'Enclos modulaire avec porte verrouillable', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-lapin-modulaire-avec-porte-verrouillable' },
      { id: '3-19', name: 'Enclos pliable avec fermeture éclair', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-lapin-pliable-avec-fermeture-eclair' },
      { id: '3-20', name: 'Enclos pliable intérieur/extérieur en PVC', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-lapin-pliable-interieurexterieur-en-pvc' },
      { id: '3-21', name: 'Enclos Relaxdays 725x110x74 cm', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-lapin-relaxdays-725x110x74-cm' },
      { id: '3-22', name: 'Enclos sur pieds avec niche', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-lapin-sur-pieds-avec-niche' },
      { id: '3-23', name: 'Enclos XXL avec porte pour intérieur', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-lapin-xxl-avec-porte-pour-interieur' },
      { id: '3-24', name: 'Enclos modulable pour petits animaux Eugad', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-modulable-pour-petits-animaux-eugad' },
      { id: '3-25', name: 'Enclos octogonal pour petits animaux', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-octogonal-pour-petits-animaux' },
      { id: '3-26', name: 'Enclos pour chien en tissu Oxford', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-pour-chien-en-tissu-oxford' },
    ],
  },
  {
    id: 'parcs-lapin',
    name: 'Parcs Lapin',
    products: [
      { id: '4-1', name: 'Parc intérieur', rating: 4.0, comment: 'Très bon produit.', url: 'https://clapier-lapin.pro/enclos-lapin-2-niveaux-gris-107x72x72-cm' },
      { id: '4-2', name: 'Parc extérieur', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/enclos-lapin-avec-balcon-et-etage' },
      { id: '4-3', name: 'Parc modulable', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/enclos-lapin-avec-cadre-metal-galvanise' },
      { id: '4-4', name: 'Parc pliable', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/enclos-lapin-bois-carre-avec-couvercle' },
      { id: '4-5', name: 'Parc avec toit', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/enclos-lapin-extensible-interieur-145x74-cm' },
      { id: '4-6', name: 'Parc XXL', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/enclos-lapin-exterieur-60-cm-avec-tapis-oxford' },
      { id: '4-7', name: 'Parc extérieur bois avec 2 espaces', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/enclos-lapin-exterieur-bois-avec-2-espaces' },
      { id: '4-8', name: 'Parc extérieur en acier galvanisé', rating: 4.5, comment: 'Excellent produit!', url: 'https://clapier-lapin.pro/enclos-lapin-exterieur-en-acier-galvanise' },
    ],
  },
];

//export default categories;
module.exports = categories;